export { default as bleed } from './hemorrhage.png';
export { default as hemorrhage } from './hemorrhage.png';
export { default as frostbite } from './frostbite.png';
export { default as frost } from './frostbite.png';
export { default as poison } from './poison.png';
export { default as rot } from './rot.png';
export { default as death } from './death.png';
export { default as sleep } from './sleep.png';
export { default as madness } from './madness.png';
